services:
  dockerdbpsql:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=karatedb
      - POSTGRES_USER=karateuser
      - POSTGRES_PASSWORD=karateuser
    ports:
      - "5442:5432"
    restart: on-failure
  karateapp:
    build:
      context: .
    depends_on:
      - dockerdbpsql
    environment:
      - DB_URL=dockerdbpsql
      - DB_PORT=5432
    ports:
      - "80:8080"