spring:
  datasource:
    name: karatedb
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5442}/karatedb
    username: karateuser
    password: karateuser
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  flyway:
    clean-disabled: false