drop table if exists student cascade;

drop table if exists student_training_list cascade;

drop table if exists trainer cascade;

drop table if exists training cascade;

drop table if exists training_student cascade;

create table student
(
    id             bigint generated by default as identity,
    date_of_birth  date,
    is_student     boolean not null,
    name           varchar(255),
    std_rank       varchar(255),
    started_karate date,
    primary key (id)
);

create table trainer
(
    id       bigint generated by default as identity,
    name     varchar(255),
    trn_rank varchar(255),
    primary key (id)
);

create table training
(
    id           bigint generated by default as identity,
    name         varchar(255),
    starts_at    time,
    ends_at      time,
    location     varchar(255),
    training_day varchar(255),
    trainer_id   bigint,
    primary key (id)
);

create table training_student
(
    training_id bigint not null,
    student_id  bigint not null
);

alter table if exists training
    add constraint FK7r3b25ygw5bdjamojskmpk0b9
        foreign key (trainer_id)
            references trainer
;

alter table if exists training_student
    add constraint FKg30d1hddnmwj7qbu7iubguwlg
        foreign key (student_id)
            references student
;

alter table if exists training_student
    add constraint FKo8um3a5gjdhvsnlg3ymrchpwe
        foreign key (training_id)
            references training
;